[world]
name = "Warpack Masters"
description = "Warpack Masters is a competitive Player-versus-Player (PvP) game that combines inventory management and autobattler mechanics within a captivating fantasy theme."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://impulsedao.xyz/warpacks/"
seed = "warpack_masters_v2"

[world.socials]
x = "https://x.com/WarpackMasters"
discord = "https://discord.gg/tjJJHc7JtP"
github = "https://github.com/0xasten/warpack-Masters/"
telegram = ""

[namespace]
default = "Warpacks"

[env]
rpc_url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_9/iOVGW3WTTEPV8_IPJI5X68y5_lMStBKN"
# Your Sepolia account
account_address = "YOUR_SEPOLIA_ACCOUNT_ADDRESS_HERE"
private_key = "YOUR_PRIVATE_KEY_HERE"

[writers]
"Warpacks" = ["Warpacks-actions", "Warpacks-dummy_system", "Warpacks-fight_system", 
    "Warpacks-item_system", "Warpacks-shop_system", "Warpacks-recipe_system", 
    "Warpacks-config_system", "Warpacks-token_factory", "Warpacks-storage_bridge"]

[init_call_args]
"Warpacks-config_system" = ["0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"]

[migration]
skip_contracts = [
    "warpack_masters::externals::erc20",
]