world_address = "0x07c7e6cbe015e7a1ee77c4e29b859894c8eae03ac1ff69361df6bd8c262c9d47"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[indexing]
preconfirmed = true
namespaces = ["Warpacks"]
external_contracts = true

[server]
http_addr = "0.0.0.0"
http_port = 8080
http_cors_origins = ["*"]

[relay]
port = 9090
webrtc_port = 9091
websocket_port = 9092

[grpc]
grpc_addr = "0.0.0.0"
grpc_port = 50051
